import type { NextPage } from 'next'
import Head from 'next/head'
import { trpc } from '@/utils/trpc';

export default function Home() {
  const {data, isLoading} = trpc.hello.useQuery({ text: 'client' });
  if (isLoading) return <div>Loading...</div>;
  if (data) return <div>{data.greeting}</div>

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1>hello</h1> 

    </div>
  );
}


